import { type Metadata } from 'next';
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs';
import {
    SidebarInset,
    SidebarProvider,
    SidebarRail,
    SidebarTrigger,
} from '@/components/ui/sidebar';
import { Toaster } from "@/components/ui/sonner"
import { AppSidebar } from '@/app/app-sidebar';
import { Geist, Geist_Mono } from 'next/font/google';
import ReactQueryProvider from "@/providers/ReactQueryProvider"
import './globals.css';
import { ThemeProvider } from '@/components/block/theme-provider';
import { NavigationMenuDemo } from '@/components/block/navigation-menu';
import { Separator } from '@/components/ui/separator';
import LandingPage from '@/components/block/landing-page';
import AppHeader from '@/components/block/app-header';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
    display: 'swap',
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider afterSignOutUrl={'/'} signInForceRedirectUrl={'/home'}>
            <html lang="en" 
            suppressHydrationWarning 
            className={`${geistSans.variable} ${geistMono.variable} antialiased` }>
                <body className="min-h-screen bg-background">
                <ReactQueryProvider>

                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="relative flex min-h-screen flex-col">
                            <main className="flex-1">{children}</main>
                            <Toaster />
                        </div>
                    </ThemeProvider>
                </ReactQueryProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
